### ISSUE TITLE
'Failed to run synchronizer' errors when extracting over HTTP

### ISSUE THREAD

**Issue by okdana** [systemd/casync#112]
Not sure if i'm just being silly here or what.

I'm experimenting with `casync`, trying to extract over HTTP a `caidx` which is basically an Ubuntu server image. Both the server and the client are running Ubuntu 16.04 (Xenial), with `casync` built from `master` ([this commit](https://github.com/systemd/casync/commit/2d5f00459c5d2318d7eff6b9fb22009fd825eab0), specifically). The server is offering the files via HTTP using a pretty much out-of-the-box nginx set-up.

File system on server:
```
% ls -Al /srv/casync
total 4124
-rw-r--r--     1 root root 1237504 Nov 27 23:43 fw.caidx
-rw-r--r--     1 root root 1196024 Nov 27 23:39 fw2.caidx
-rw-r--r--     1 root root 1240224 Nov 27 23:52 fw3.caidx
drwxr-xr-x 29324 root root  540672 Nov 27 23:52 default.castr/
```

I have a similar image already on my client's disk, so i'm trying to seed with that. When i do so, i find that i very consistently get a 'broken pipe' error, seemingly indicating that `casync` is failing to retrieve the full index file. Here's what it looks like:

Commands run on client:
```
% sudo mkdir /data/fw
% {
> date
> sudo casync -v --seed=/data/myfw extract http://172.17.1.213/fw.caidx /data/fw
> date
> } 2>&1 | tee casync.log
```

Output on client:
```
Tue 28 Nov 00:57:15 CST 2017
Acquiring http://172.17.1.213/fw.caidx...
Seeding ./
Seeded ./
Seeding ./
Seeding bin
...
Seeded var/www
Seeded var
Seeding vmlinuz
Seeded vmlinuz
Seeded ./
Failed to acquire http://172.17.1.213/fw.caidx
Failed to run synchronizer: Broken pipe
Tue 28 Nov 01:00:08 CST 2017
```

Web-server logs on server:
```
172.17.66.1 - - [28/Nov/2017:00:58:15 -0600] "GET /fw.caidx HTTP/1.1" 200 493499 "-" "-"
```

Note that `493499` is not the full size of `fw.caidx`. (Note also that the error is not actually returned until it finishes the seeding process almost 2 minutes later — that's kind of bothersome.)

I keep running this over and over and keep getting similar results — `casync` only ever gets between maybe 400 and 700 kB of the index file, and then it gives that broken-pipe error. If i retrieve the index file with `curl` it works fine, i get the full size shown in the log and it matches on the client.

I thought i would try the same thing but without the seeding bit, and it does seem to get further (in that i have a bunch of files extracted on the client), but now i get a different error:

Commands run on client:
```
% sudo mkdir /data/fw
% {
> date
> sudo casync -v extract http://172.17.1.213/fw.caidx /data/fw
> date
> } 2>&1 | tee casync.log
```

Output on client:
```
Tue 28 Nov 01:06:43 CST 2017
Acquiring http://172.17.1.213/fw.caidx...
Seeding ./
Seeded ./
Acquiring http://172.17.1.213/default.castr/7634/7634a8d3b747c84fa60c779497e95793a346603553af87b208e2abe0a59b620d.cacnk...
Acquiring http://172.17.1.213/default.castr/25fa/25fa6d80a0f122d8f0473dda8bf9a8d8703a875107e299b6f84730e11020928d.cacnk...
Acquiring http://172.17.1.213/default.castr/fd27/fd2741d59d832c5e81afd57122d0c648a5189cd3775d3df321fb6fcff243e37e.cacnk...
Extracting ./
Using feature flags: 32bit-uids user-names nsec-time symlinks device-nodes fifos sockets flag-hidden flag-system flag-archive flag-append flag-noatime flag-compr flag-nocow flag-dirsync flag-immutable flag-sync flag-nocomp flag-projinherit flag-subvolume flag-subvolume-ro xattrs acl selinux fcaps
Excluding files with chattr(1) -d flag: yes
Excluding submounts: no
Digest algorithm: sha512-256
...
Extracting etc/depmod.d/ubuntu.conf
Extracted etc/depmod.d/ubuntu.conf
Extracted etc/depmod.d
Extracting etc/dhcp
Extracting etc/dhcp/ddns-keys
Extracted etc/dhcp/ddns-keys
Failed to run synchronizer: No such process
Tue 28 Nov 01:06:52 CST 2017
```

The Web-server logs show something like 1000 chunks being fetched. I spot-checked the last few and they all seem to have returned the correct size, so it's not that. I guess don't know what the 'process' it's referring to is.

Any ideas as to how i could troubleshoot further? Thanks!

**Comment by poettering** [comment]
can you check if current git from today makes this work? I ran into a similar bug but with today's version it disappeared for me. (and I am not entirely sure why)

**Comment by ejoerns** [comment]
Could be related to what I came across with #121

**Comment by poettering** [comment]
Fix waiting in #124.

**Comment by okdana** [comment]
Sorry i haven't got back to you on this; my test machines were decommissioned and i haven't got around to setting it all back up. I'll try to test again soon. Thank you!

**Comment by okdana** [comment]
Hey, i was able to get back to this today. Tried again with PR #124 applied to `master`.

In the *unseeded* case, i still get *No such process*. However, i tried adding `--without=user-names` per the exchange in #121, and that seems to sort it. So i guess that's probably all that was. Thanks @ejoerns!

As far as the *seeded* case, there's still an issue there, and `--without=user-names` doesn't fix it. The error message is different — i now get *Permission denied* instead of *Broken pipe* — but otherwise the behaviour is the same. The error appears immediately after the seeding finishes, and the Web-server log (i used Apache instead of nginx this time) shows that only ~600 kB of the index file was retrieved. Maybe there's some other difference in the file structure that's causing it to bail at that point? I'm not sure.
