### ISSUE TITLE
casync does not work on fuse mount ?

### ISSUE THREAD

**Issue by limbo127** [systemd/casync#116]
Hello,
casync list /mnt/
Failed to run synchronizer: Invalid argument

/mnt is fuse block parition ( ntfs3g )   .
qcow image as mount as block device via qemu-nbd, then mount via ntfs3g
/dev/nbd0 on /mnt type fuseblk (rw,nosuid,nodev,allow_other,blksize=4096) 

Regards, 
Nicolas

**Comment by poettering** [comment]
casync should work fine on fuse, in fact we explicitly test for this: "casync mount" itself is a fuse file system, and our CI test ensure that what is exposed as that will result it in the bit-perfect identical image as the original. 

That said, specific fuse file systems might differ substantially in the functionality they provide, and might need some tweaking to make work for casync. It's just a matter of testing this and looking what fails and making it work. 

Note that casync even stores DOS-style file flags if possible, hence it actually provides some specific support for windows-style file systems already, and hence should be quite friendly with NTFS too, in theory.

**Comment by limbo127** [comment]
Ok, so how can help you to identify this issue ?
Regards, 
Nicolas Prochazka

/dev/nbd0 on /mnt type fuseblk (rw,nosuid,nodev,allow_other,blksize=4096)

qemu-nbd -c /dev/nbd0 -s -P 2 /data/upload/CM-441c921a-5bcf-48de-a3e1-c4d997c82937-1479143958.cebox

casync  -v  list /mnt/
Selected chunk sizes: min=16384..avg=65536..max=262144
Failed to run synchronizer: Invalid argument

]casync  -v make /data/w10.catar /mnt/
Selected chunk sizes: min=16384..avg=65536..max=262144
Failed to run synchronizer: Invalid argument

**Comment by poettering** [comment]
Fix waiting in #120.

**Comment by poettering** [comment]
I merged #120 now. Closing
