### ISSUE TITLE
FTBFS on Fedora Rawhide

### ISSUE THREAD

**Issue by ignatenkobrain** [systemd/casync#133]
```
 8/16 test-cachunker                          FAIL     2.71 s
--- command ---
/builddir/build/BUILD/casync-2/x86_64-redhat-linux-gnu/test-cachunker
--- stderr ---
../test/test-cachunker.c:131 (test_set_size): assertion failed:y.chunk_size_avg == 4*1024
```

This is happening with latest tagged version (2)..

**Comment by keszybz** [comment]
Also happens with git master…

**Comment by fweimer** [comment]
Looks like `casync` use `-ffast-math`, so these things are to be expected.

**Comment by poettering** [comment]
@fweimer ah, thanks for the hint!

I have prepped #136 now, which drops -ffast-math from our build. Given that we care about reproducibility we shouldn't use stuff that comes to different results on different archs, compilers and versions thereof.
