### ISSUE TITLE
[Question] Can we change the temp place where casync extracts to during extraction?

### ISSUE THREAD

**Issue by Peirl** [systemd/casync#155]
Hi,

I am trying to extract a file using casync and I am running into space issues during extraction. 
I am trying to extract the file into partition 5, where there is plenty of space, but casync seems to be using partition 2 during the extraction. After a while it gives a Failed to run synchronizer: out of disk space error. 

Is there a way for me to specify where I want casync to work on in the intermediate process?

Thanks.

**Comment by mihais** [comment]
Try this, and make sure casync has write access to TMPDIR:
export TMPDIR=/part5_mount_point
casync extract ....

**Comment by Peirl** [comment]
Thanks! It works. ^^
