### ISSUE TITLE
Read-only filesystem

### ISSUE THREAD

**Issue by moonwolf-github** [systemd/casync#201]
I'm running casync on RO squashfs filesystem (ran from initrd) to populate empty disk and i'm getting error:
```
# casync extract http://server/test.caibx /dev/sda
Failed to run synchronizer: Read-only file system
```
Is there option to run it that way or any workaround?

**Comment by poettering** [comment]
casync wants to write to /var/tmp to temporarily store chunks it just downloaded. Is that writable?

**Comment by moonwolf-github** [comment]
Now it is, thanks! Can't say it's working because now it says "Can't acqurie" and "Broken pipe". But this is separate issue i guess.
