### ISSUE TITLE
Can this replace zsync?

### ISSUE THREAD

**Issue by probonopd** [systemd/casync#22]
With __zsync__, one `.zsync` file is all that needs to be hosted on the server, in addition to the file to be distributed. Can the same be achieved with __casync__?

Use case would be [AppImageUpdate](https://github.com/AppImage/AppImageUpdate) which is currently using zsync.

**Comment by poettering** [comment]
No, zsync works differently: it expects that the file to download is always around on the server in its original form, and that HTTP GET Range requests are availale to get arbitrary parts of it.

casync OTOH never stores the original file on the server. Instead it stores individually compressed blocks as separate files on the server. the "caidx" file then lets you know how to concatenate them to get the original file back. 

The major effective difference of the two models becomes visible if you offer a number of very similar images on the same server (such as: multiple subsequent versions of the same package, or app images of a variety of apps that all contain their own dependencies and thus largely similar data) then the casync approach permits you to share the same blocks between each. casync is hence specifically designed for a world with a high frequency of app updates, and for for packaged apps that carry their own deps (like containers generally do it).

There are more differences beyond that though, one important one: casync's block files are dumb, they require now GET Range requests. This makes them friendly towards CDNs, and as the average block size can be controlled you have a nice knob to control how many GET requests are issued.

Summary: no, casync is not a 1:1 replacement (why even? — zsync is fine software), it serves a different, but similar usecase.
