### ISSUE TITLE
make libfuse optional again

### ISSUE THREAD

**Issue by zonque** [systemd/casync#48]
`meson build` gives me

```
Meson encountered an error in file meson.build, line 105, column 8:
Native dependency 'fuse' not found
```

This used to work in earlier versions.

**Comment by zonque** [comment]
@keszybz any idea?

**Comment by ignatenkobrain** [comment]
@zonque `-Dfuse=false`

**Comment by zonque** [comment]
Well, I know, but that should be the default.

**Comment by keszybz** [comment]
It's on purpose: you can disable the dependency explicitly, otherwise it is required. Pretty much everybody wants it, except for very constrained systems.

**Comment by poettering** [comment]
all deps need to be on by default, so all is good. hence I figure there's nothing to fix here. Closing.
