### ISSUE TITLE
Dump stats about downloaded content

### ISSUE THREAD

**Issue by ignatenkobrain** [systemd/casync#50]
It's useful to see how much data you saved using casync without using tcpdump or any other tools ;)

**Comment by Spindel** [comment]
I'm currently evaluating casync here, and it would be very nice to be able to do this, both online, and offline.

I want to work on minimizing the delta sizes,  with a tool like xdelta3,  I can see the final size of the delta, which doesn't seem to be the case with casync.

**Comment by Spindel** [comment]
Brief work with strace(3) shows that  casync is an order of magnitude  less efficient than xdelta3 on squashfs files.

**Comment by Spindel** [comment]
Methodology:
```
casync make -v  --chunk-size=131072 target.squashfs.xaibx target.squashfs
strace -o strace.log casync extract -v --chunk-size=131072 --seed=previous.squashfs  target.squashfs.caibx target.squashfs.extracted
```

Then simply traversing the strace log  and seeing the size read()  returns from .xz files:
`107 787 944 bytes`, compared to xdelta3 for the same dataset (2.7MiB)  it is rather on the high end.
