### ISSUE TITLE
Unbounded amounts of "Chunk cache is not up-to-date, ignoring" log spam

### ISSUE THREAD

**Issue by charles-dyfis-net** [systemd/casync#97]
When performing a multi-GB extraction (`casync extract --what=blob-index root.caidx root.catar`) to a preexisting output file, I have literally many tens of thousands of lines of `Chunk cache is not up-to-date, ignoring.`. Without details on how this is actionable to the user, it's effectively just spam.

Perhaps this should only be emitted up to once per file with `-v` in use, or up to once per session without `-v`?

**Comment by poettering** [comment]
Fixed by 9cc647b80081b128dd28e590e3bf64748cf2684c. Closing.
